--
-- Target: PostgreSQL 
-- Syntax: psql \i filename
-- 
-- Date  : May 24 2024 15:01
-- Script Generated by Database Design Studio 2.21.3 
--
-- Create Table    : 'Employee'   
-- EmpID           :  
-- name            :  
-- start_date      :  
-- birthdate       :  
-- department      : dept
--
CREATE SEQUENCE if NOT EXISTS seq_Employee_EmpID
    INCREMENT 1
    START 1;

CREATE TYPE dept AS ENUM ('Library', 'Desk', 'Archives', 'Management', 'Security');

CREATE TYPE team AS ENUM ('Library', 'Desk', 'Archives', 'Security');

CREATE TYPE days AS ENUM ('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');

CREATE TYPE genre AS ENUM ('children', 'mystery', 'fantasy', 'romance', 'science fiction', 'thriller', 'historical fiction', 'biography', 'self-help', 'cookbook');

CREATE TYPE specialty AS ENUM ('children', 'mystery', 'fantasy', 'romance', 'science fiction', 'thriller', 'historical fiction', 'biography');

CREATE TYPE post AS ENUM ('Front door', 'Back door', 'Side door', 'Main floor', 'Archives');

CREATE TABLE if NOT EXISTS "Employee" (
    EmpID          INTEGER DEFAULT NEXTVAL('seq_Employee_EmpID') NOT NULL,
    name           VARCHAR NOT NULL,
    start_date     DATE NOT NULL,
    birthdate      DATE NOT NULL,
    department     dept NOT NULL,
CONSTRAINT pk_Employee PRIMARY KEY (EmpID));


--
-- Create Table    : 'Shift'   
-- day_of_week     : 
-- timeslot        :  
--
CREATE TABLE if NOT EXISTS "Shift" (
    day_of_week    days NOT NULL,
    timeslot       INTERVAL NOT NULL,
CONSTRAINT pk_Shift PRIMARY KEY (day_of_week,timeslot));


--
-- Create Table    : 'Librarian'   
-- EmpID           :  (references Employee.EmpID)
-- specialty       : genres 
--
CREATE TABLE if NOT EXISTS "Librarian" (
    EmpID          INTEGER NOT NULL,
    specialty      genre NOT NULL,
CONSTRAINT pk_Librarian PRIMARY KEY (EmpID),
CONSTRAINT fk_Librarian FOREIGN KEY (EmpID)
    REFERENCES "Employee" (EmpID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


--
-- Create Table    : 'Preserver'   
-- EmpID           :  (references Employee.EmpID)
-- specialty       : genres 
--
CREATE TABLE if NOT EXISTS "Preserver" (
    EmpID          INTEGER NOT NULL,
    specialty      specialty NOT NULL,
CONSTRAINT pk_Preserver PRIMARY KEY (EmpID),
CONSTRAINT fk_Preserver FOREIGN KEY (EmpID)
    REFERENCES "Employee" (EmpID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


--
-- Create Table    : 'Secratary'   
-- EmpID           :  (references Employee.EmpID)
--
CREATE TABLE if NOT EXISTS "Secratary" (
    EmpID          INTEGER NOT NULL,
CONSTRAINT pk_Secratary PRIMARY KEY (EmpID),
CONSTRAINT fk_Secratary FOREIGN KEY (EmpID)
    REFERENCES "Employee" (EmpID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


--
-- Create Table    : 'Manager'   
-- EmpID           :  (references Employee.EmpID)
-- team            : dept/team 
--
CREATE TABLE if NOT EXISTS "Manager" (
    EmpID          INTEGER NOT NULL,
    team           team NOT NULL,
CONSTRAINT pk_Manager PRIMARY KEY (EmpID),
CONSTRAINT fk_Manager FOREIGN KEY (EmpID)
    REFERENCES "Employee" (EmpID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


--
-- Create Table    : 'Security'   
-- EmpID           :  (references Employee.EmpID)
-- location        : guard posts 
--
CREATE TABLE if NOT EXISTS "Security" (
    EmpID          INTEGER NOT NULL,
    location       post NOT NULL,
CONSTRAINT pk_Security PRIMARY KEY (EmpID),
CONSTRAINT fk_Security FOREIGN KEY (EmpID)
    REFERENCES "Employee" (EmpID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


--
-- Create Table    : 'Works'   
-- EmpID           :  (references Employee.EmpID)
-- day_of_week     :  (references Shift.day_of_week)
-- timeslot        :  (references Shift.timeslot)
--
CREATE TABLE Works (
    EmpID          INTEGER NOT NULL,
    day_of_week    days NOT NULL,
    timeslot       INTERVAL NOT NULL,
CONSTRAINT pk_Works PRIMARY KEY (EmpID,day_of_week,timeslot),
CONSTRAINT fk_Works FOREIGN KEY (EmpID)
    REFERENCES "Employee" (EmpID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
CONSTRAINT fk_Works2 FOREIGN KEY (day_of_week,timeslot)
    REFERENCES "Shift" (day_of_week,timeslot)
    MATCH FULL
    ON DELETE CASCADE
    ON UPDATE CASCADE);

--
-- Permissions for: 'public'
--
GRANT ALL ON "Employee" TO GROUP public;
GRANT ALL ON "Shift" TO GROUP public;
GRANT ALL ON "Librarian" TO GROUP public;
GRANT ALL ON "Preserver" TO GROUP public;
GRANT ALL ON "Secratary" TO GROUP public;
GRANT ALL ON "Manager" TO GROUP public;
GRANT ALL ON "Security" TO GROUP public;

