--
-- Target: PostgreSQL 
-- Syntax: psql \i filename
-- 
-- Date  : May 24 2024 15:01
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Table    : 'Security'   
--
DROP TABLE Security;

--
-- Drop Table    : 'Manager'   
--
DROP TABLE Manager;

--
-- Drop Table    : 'Secratary'   
--
DROP TABLE Secratary;

--
-- Drop Table    : 'Preserver'   
--
DROP TABLE Preserver;

--
-- Drop Table    : 'Librarian'   
--
DROP TABLE Librarian;

--
-- Drop Table    : 'Shift'   
--
DROP TABLE Shift;

--
-- Drop Table    : 'Employee'   
--
DROP TABLE Employee;

DROP SEQUENCE seq_Employee_EmpID;
