--
-- Target: PostgreSQL 
-- 
-- Date  : May 24 2024 15:01
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Load Table : 'Employee' 
--
COPY Employee
    FROM Employee.txt
        WITH DELIMITER AS ',';

--
-- Load Table : 'Shift' 
--
COPY Shift
    FROM Shift.txt
        WITH DELIMITER AS ',';

--
-- Load Table : 'Librarian' 
--
COPY Librarian
    FROM Librarian.txt
        WITH DELIMITER AS ',';

--
-- Load Table : 'Preserver' 
--
COPY Preserver
    FROM Preserver.txt
        WITH DELIMITER AS ',';

--
-- Load Table : 'Secratary' 
--
COPY Secratary
    FROM Secratary.txt
        WITH DELIMITER AS ',';

--
-- Load Table : 'Manager' 
--
COPY Manager
    FROM Manager.txt
        WITH DELIMITER AS ',';

--
-- Load Table : 'Security' 
--
COPY Security
    FROM Security.txt
        WITH DELIMITER AS ',';

