--
-- Target: PostgreSQL 
-- 
-- Date  : Aug 01 2024 17:52
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Load Table : 'Shift' 
--
COPY "Shift"
    FROM "Shift.txt"
        WITH DELIMITER AS ',';

--
-- Load Table : 'Wages' 
--
COPY "Wages"
    FROM "Wages.txt"
        WITH DELIMITER AS ',';

--
-- Load Table : 'People' 
--
COPY "People"
    FROM "People.txt"
        WITH DELIMITER AS ',';

--
-- Load Table : 'Employee' 
--
COPY "Employee"
    FROM "Employee.txt"
        WITH DELIMITER AS ',';

--
-- Load Table : 'Librarian' 
--
COPY "Librarian"
    FROM "Librarian.txt"
        WITH DELIMITER AS ',';

--
-- Load Table : 'Preserver' 
--
COPY "Preserver"
    FROM "Preserver.txt"
        WITH DELIMITER AS ',';

--
-- Load Table : 'Secratary' 
--
COPY "Secratary"
    FROM "Secratary.txt"
        WITH DELIMITER AS ',';

--
-- Load Table : 'Manager' 
--
COPY "Manager"
    FROM "Manager.txt"
        WITH DELIMITER AS ',';

--
-- Load Table : 'Security' 
--
COPY "Security"
    FROM "Security.txt"
        WITH DELIMITER AS ',';

--
-- Load Table : 'Works' 
--
COPY "Works"
    FROM "Works.txt"
        WITH DELIMITER AS ',';

--
-- Load Table : 'Payment' 
--
COPY "Payment"
    FROM "Payment.txt"
        WITH DELIMITER AS ',';

--
-- Load Table : 'Members' 
--
COPY "Members"
    FROM "Members.txt"
        WITH DELIMITER AS ',';

