--
-- Target: PostgreSQL 
-- Syntax: psql \i filename
-- 
-- Date  : Aug 01 2024 17:52
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Table    : 'Members'   
--
DROP TABLE "Members";

DROP SEQUENCE seq_Members_ID;
--
-- Drop Table    : 'Payment'   
--
DROP TABLE "Payment";

DROP SEQUENCE seq_Payment_CashflowID;
--
-- Drop Table    : 'Works'   
--
DROP TABLE "Works";

--
-- Drop Table    : 'Security'   
--
DROP TABLE "Security";

--
-- Drop Table    : 'Manager'   
--
DROP TABLE "Manager";

--
-- Drop Table    : 'Secratary'   
--
DROP TABLE "Secratary";

--
-- Drop Table    : 'Preserver'   
--
DROP TABLE "Preserver";

--
-- Drop Table    : 'Librarian'   
--
DROP TABLE "Librarian";

--
-- Drop Table    : 'Employee'   
--
DROP TABLE "Employee";

DROP SEQUENCE seq_Employee_EmpID;
--
-- Drop Table    : 'People'   
--
DROP TABLE "People";

DROP SEQUENCE seq_People_Person_ID;
--
-- Drop Table    : 'Wages'   
--
DROP TABLE "Wages";

DROP SEQUENCE seq_Wages_ID;
--
-- Drop Table    : 'Shift'   
--
DROP TABLE "Shift";

DROP TYPE IF EXISTS dept;
DROP TYPE IF EXISTS team;
DROP TYPE IF EXISTS days;
DROP TYPE IF EXISTS genre;
DROP TYPE IF EXISTS specialty;
DROP TYPE IF EXISTS post;
